### ISSUE TITLE
Images should be versioned

### ISSUE THREAD

**Issue by laserb** [vshn/terraform-eks-rancher#15]
## Issue
The docker images are currently not labeled and only latest is available.
All pipelines using this image just use the latest image.

The terraform version is outdated and newer providers and modules are no longer compatible with it.
Upgrading the terraform version in the image and releasing a new docker image is risky and has the potential to break pipelines that use latest.

## Expected
* Commits and resulting docker images should be tagged. Use a release pipeline to publish docker images.
* Safe migration path for current pipelines using latest

## Known workaround
In order to avoid updating the docker image it is possible to use an upstream terraform docker image and install the missing tools in a `before_script` step.

**Comment by CLNRMN** [comment]
Dockerfile is under control of Renovate.
